image: alpine
  
jobs:
  main:
    steps:
      - test: git clone https://github.com/screwdriver-cd-test/quickstart-nodejs.git
      - command: /opt/sd/sd-step exec core/git git clone https://github.com/screwdriver-cd-test/quickstart-nodejs.git 1>/dev/null
      - command-v: /opt/sd/sd-step exec core/git git clone https://github.com/screwdriver-cd-test/functional-git.git --pkg-version 2.7.4 1>/dev/null
