jobs:
  main:
    image: ruby:2
    steps:
      - command: /opt/sd/sd-step exec core/node node hello.js >/dev/null
      - command-v: /opt/sd/sd-step exec core/node node index.js --pkg-version 5.6.0 >/dev/null
      # - version-error: /opt/sd/sd-step exec core/node node hello.js --pkg-version ^5.6.0 1>/dev/null
  sub:
    image: ruby:2
    steps:
      - command: /opt/sd/sd-step exec core/node node index.js >/dev/null
