jobs:
  main:
    image: ruby:2
    steps:
      - command: /opt/sd/sd-step exec core/node node hello.js 1>/dev/null
      - command-v: /opt/sd/sd-step exec core/node node index.js --pkg-version 5.6.0 1>/dev/null
